models.py
'''
User
'''

from app import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128), unique=True)
    password = db.Column(db.String(128))
    name = db.Column(db.String(256))
    registered = db.Column(db.Date)

class Symbol(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(16))

app.py
from flask import Flask

# Database handling
from flask_sqlalchemy import SQLAlchemy
# db must be instantiated very early, because some imports already will use
#   the instantiated db
db = SQLAlchemy()

# Authentication handling
from flask_login import LoginManager

# Routes
from routes.auth import auth as auth_blueprint
from routes.main import main as main_blueprint
from routes.symbol import symbol as symbol_blueprint

# Migrations
from flask_migrate import Migrate

# Check environment variables, so is more secure set some information
#   as os environment variable rather than depends upon code
import os

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('TMT_SECRET_KEY')

db_user = os.environ.get('TMT_DB_USER')
db_password = os.environ.get('TMT_DB_PASSWORD')
db_host = os.environ.get('TMT_DB_HOST')
db_database = os.environ.get('TMT_DB_DATABASE')
if 'TMT_DB_PORT' in os.environ:
    db_host += ":" + os.environ.get('TMT_DB_PORT')
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://{}:{}@{}/{}'.format(db_user, db_password, db_host, db_database)

db.init_app(app)

from models import User

app.register_blueprint(auth_blueprint)
app.register_blueprint(main_blueprint)
app.register_blueprint(symbol_blueprint)

migrate = Migrate(app, db)

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

routes/auth.py
'''
GET login
POST login
GET signup
POST signup
GET logout
POST login
'''

from flask import \
    Blueprint,\
    render_template,\
    url_for,\
    redirect,\
    request,\
    flash
from werkzeug.security import generate_password_hash, check_password_hash
from models import User
from app import db
from flask_login import login_user, logout_user, login_required
from routes.commons import hidden_to_logged

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    hidden_to_logged()

    return render_template('login.html')

@auth.route('/signup')
def signup():
    hidden_to_logged()

    return render_template('signup.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))



@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

routes/commons.py
from flask_login import current_user
from flask import url_for, redirect

def hidden_to_logged():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))

routes/main.py
'''
GET /
GET profile
'''

from flask import Blueprint, request
from flask import render_template
from flask_login import login_required, current_user

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name, name2="justest")

routes/symbol.py
from flask import Blueprint, \
    render_template, \
    redirect, \
    url_for, \
    request, \
    flash
from models import Symbol
from app import db
from flask_login import current_user

symbol = Blueprint('symbol', __name__)

@symbol.route('/symbol')
def index():

    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    return render_template('symbol/index.html', models=Symbol.query.all())

@symbol.route('/symbol', methods=['POST'])
def store():

    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    new_symbol = Symbol(symbol=request.form.get('symbol'))

    db.session.add(new_symbol)
    db.session.commit()

    flash('{} just created.'.format(new_symbol.symbol))
    
    return redirect(url_for('symbol.create'))

@symbol.route('/symbol/create')
def create():

    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
        
    return render_template('symbol/create.html')

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flask Auth Example</title>
  <link rel="stylesheet" href="/static/css/styles.css" />
  <link rel="shortcut icon" href="/static/money_icon.png" type="image/x-icon" />
</head>

<body>
  <section class="is-fullheight">

    <div class="head">

      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
            data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-menu">
          <div class="navbar-start">

            <a href="{{ url_for('main.index') }}" class="navbar-item">
              Home
            </a>

            {% if current_user.is_authenticated %}
            <a href="{{ url_for('main.profile') }}" class="navbar-item">
              Profile
            </a>
            {% endif %}

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Symbols
              </a>

              <div class="navbar-dropdown">
                <a href="{{ url_for('symbol.index') }}" class="navbar-item">
                  List
                </a>
                <a href="{{ url_for('symbol.create') }}" class="navbar-item">
                  Create
                </a>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">

                {% if not current_user.is_authenticated %}
                <a href="{{ url_for('auth.signup') }}" class="button">
                  Sign up
                </a>
                {% endif %}

                {% if not current_user.is_authenticated %}
                <a href="{{ url_for('auth.login') }}" class="button">
                  Login
                </a>
                {% endif %}

                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}" class="button">
                  Logout
                </a>
                {% endif %}

              </div>
            </div>
          </div>
        </div>
      </nav>


    </div>

    <div class="hero-body">
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </section>

  <script src="/static/js/bundle.js"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  The month trader
</h1>
<h2 class="subtitle">
  Application for facilitates earnings inside month.
</h2>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
<h1>Hi just again {{ name2 }}</h1>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

templates/symbol/create.html
{% extends "base.html" %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="notification is-primary form-notification-normal">
        {{ messages[0] }}
    </div>
{% else %}
    <div class="notification is-invisible form-notification-normal">
      &nbsp;
    </div>
{% endif %}
{% endwith %}

<h3 class="title">
  Add a symbol
</h1>

<div class="column is-12 is-offset">

  
    <form method="POST" action="/symbol">

      <div class="field">
        <div class="control">
          <input name="symbol" type="text" class="input">
        </div>
      </div>

      <button class="button is-block is-info is-fullwidth">Add</button>

    </form>
</div>
{% endblock %}

templates/symbol/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Symbols registered
</h1>

<ul>
  {% for model in models %}
  <li>{{ model.symbol }}</li>
  {% endfor %}
</ul>

{% endblock %}